version: "3.7"
services:
  db:
    container_name: db
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ticketdb
      - MYSQL_USER=tkuser
      - MYSQL_PASSWORD=tkpass
    ports:
      - "3306:3306"
