version: "3.7"
services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbticket
      - MYSQL_USER=tkuser
      - MYSQL_PASSWORD=tkpass
    ports:
      - "3306:3306"
